version: '3.4'

configs:
  nginx_config_6:
    file: ./conf/site.conf
  dhparams:
    file: ./dhparams.pem

networks:
  net:
    driver: overlay

services:
  frontend:
    image: ${frontend_image_name}:${frontend_image_version}
    environment:
      - BACKEND_DOMAIN=${backend_domain}
      - "BACKEND_PROTOCOL=https:"
      - SENTRY_DSN=${frontend_sentry_dsn}
      - SENTRY_TOKEN=${frontend_sentry_token}
    networks:
      - net

  backend:
    image: ${backend_image_name}:${backend_image_version}
    environment:
      - DEBUG=
      - SECRET_KEY=${backend_secret_key}
      - DB_NAME=${backend_db_name}
      - DB_USER=${backend_db_user}
      - DB_PASSWORD=${backend_db_password}
      - DB_HOST=${db_host}
      - DB_PORT=${db_port}
      - ALLOWED_HOSTS=${backend_domain},${frontend_domain}
      - QTICKETS_ENDPOINT=${qtickets_endpoint}
      - QTICKETS_TOKEN=${qtickets_token}
      - SENTRY_DSN=${backend_sentry_dsn}
      - CORS_LIST=${backend_cors_list},http://localhost:3000
    networks:
      - net

  nginx:
    image: umputun/nginx-le:1.1.0
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=${email}
      - LE_FQDN=${frontend_domain},${backend_domain},krddevdays.ru
    configs:
      - source: nginx_config_6
        target: /etc/nginx/service.conf
      - source: dhparams
        target: /etc/nginx/ssl/dhparams.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    depends_on:
      - site_frontend
      - site_backend
